package ch.cclerc.luxapp.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
class LuxColors(
    val isDark: Boolean,
    val systemBackground: Color,
    val secondarySystemBackground: Color,
    val tertiarySystemBackground: Color,
    val systemGroupedBackground: Color,
    val secondarySystemGroupedBackground: Color,
    val tertiarySystemGroupedBackground: Color,
    val systemBackgroundElevated: Color,
    val secondarySystemBackgroundElevated: Color,
    val tertiarySystemBackgroundElevated: Color,
    val label: Color,
    val secondaryLabel: Color,
    val tertiaryLabel: Color,
    val quaternaryLabel: Color,
    val systemFill: Color,
    val secondarySystemFill: Color,
    val tertiarySystemFill: Color,
    val quaternarySystemFill: Color,
    val separator: Color,
    val opaqueSeparator: Color,
    val systemGray: Color,
    val systemGray2: Color,
    val systemGray3: Color,
    val systemGray4: Color,
    val systemGray5: Color,
    val systemGray6: Color,
    val systemRed: Color,
    val systemGreen: Color,
    val systemBlue: Color,
    val systemOrange: Color,
    val systemYellow: Color,
    val systemIndigo: Color,
    val systemTeal: Color,
    val systemPurple: Color,
    val systemPink: Color,
    val systemCyan: Color
) {
    val hairline: Color = label.copy(alpha = 0.1f)
    val hairlineGray: Color = systemGray.copy(alpha = 0.1f)

    companion object {
        fun light(): LuxColors = LuxColors(
            isDark = false,
            systemBackground = Color(0xFFFFFFFF),
            secondarySystemBackground = Color(0xFFF2F2F7),
            tertiarySystemBackground = Color(0xFFFFFFFF),
            systemGroupedBackground = Color(0xFFF2F2F7),
            secondarySystemGroupedBackground = Color(0xFFFFFFFF),
            tertiarySystemGroupedBackground = Color(0xFFF2F2F7),
            systemBackgroundElevated = Color(0xFFFFFFFF),
            secondarySystemBackgroundElevated = Color(0xFFF2F2F7),
            tertiarySystemBackgroundElevated = Color(0xFFFFFFFF),
            label = Color(0xFF000000),
            secondaryLabel = Color(0xFF3C3C43).copy(alpha = 0.6f),
            tertiaryLabel = Color(0xFF3C3C43).copy(alpha = 0.3f),
            quaternaryLabel = Color(0xFF3C3C43).copy(alpha = 0.18f),
            systemFill = Color(0xFF787880).copy(alpha = 0.2f),
            secondarySystemFill = Color(0xFF787880).copy(alpha = 0.16f),
            tertiarySystemFill = Color(0xFF767680).copy(alpha = 0.12f),
            quaternarySystemFill = Color(0xFF747480).copy(alpha = 0.08f),
            separator = Color(0xFF3C3C43).copy(alpha = 0.29f),
            opaqueSeparator = Color(0xFFC6C6C8),
            systemGray = Color(0xFF8E8E93),
            systemGray2 = Color(0xFFAEAEB2),
            systemGray3 = Color(0xFFC7C7CC),
            systemGray4 = Color(0xFFD1D1D6),
            systemGray5 = Color(0xFFE5E5EA),
            systemGray6 = Color(0xFFF2F2F7),
            systemRed = Color(0xFFFF3B30),
            systemGreen = Color(0xFF34C759),
            systemBlue = Color(0xFF007AFF),
            systemOrange = Color(0xFFFF9500),
            systemYellow = Color(0xFFFFCC00),
            systemIndigo = Color(0xFF5856D6),
            systemTeal = Color(0xFF30B0C7),
            systemPurple = Color(0xFFAF52DE),
            systemPink = Color(0xFFFF2D55),
            systemCyan = Color(0xFF32ADE6)
        )

        fun dark(): LuxColors = LuxColors(
            isDark = true,
            systemBackground = Color(0xFF000000),
            secondarySystemBackground = Color(0xFF1C1C1E),
            tertiarySystemBackground = Color(0xFF2C2C2E),
            systemGroupedBackground = Color(0xFF000000),
            secondarySystemGroupedBackground = Color(0xFF1C1C1E),
            tertiarySystemGroupedBackground = Color(0xFF2C2C2E),
            systemBackgroundElevated = Color(0xFF1C1C1E),
            secondarySystemBackgroundElevated = Color(0xFF2C2C2E),
            tertiarySystemBackgroundElevated = Color(0xFF3A3A3C),
            label = Color(0xFFFFFFFF),
            secondaryLabel = Color(0xFFEBEBF5).copy(alpha = 0.6f),
            tertiaryLabel = Color(0xFFEBEBF5).copy(alpha = 0.3f),
            quaternaryLabel = Color(0xFFEBEBF5).copy(alpha = 0.18f),
            systemFill = Color(0xFF787880).copy(alpha = 0.36f),
            secondarySystemFill = Color(0xFF787880).copy(alpha = 0.32f),
            tertiarySystemFill = Color(0xFF767680).copy(alpha = 0.24f),
            quaternarySystemFill = Color(0xFF767680).copy(alpha = 0.18f),
            separator = Color(0xFF545458).copy(alpha = 0.6f),
            opaqueSeparator = Color(0xFF38383A),
            systemGray = Color(0xFF8E8E93),
            systemGray2 = Color(0xFF636366),
            systemGray3 = Color(0xFF48484A),
            systemGray4 = Color(0xFF3A3A3C),
            systemGray5 = Color(0xFF2C2C2E),
            systemGray6 = Color(0xFF1C1C1E),
            systemRed = Color(0xFFFF453A),
            systemGreen = Color(0xFF30D158),
            systemBlue = Color(0xFF0A84FF),
            systemOrange = Color(0xFFFF9F0A),
            systemYellow = Color(0xFFFFD60A),
            systemIndigo = Color(0xFF5E5CE6),
            systemTeal = Color(0xFF40C8E0),
            systemPurple = Color(0xFFBF5AF2),
            systemPink = Color(0xFFFF375F),
            systemCyan = Color(0xFF64D2FF)
        )
    }
}
