package ch.cclerc.luxapp.core

data class MaterialSymbol(val glyph: String, val fill: Float = 0f)

object SymbolMap {
    private val map: Map<String, MaterialSymbol> = mapOf(
        "airplane" to MaterialSymbol("flight"),
        "app.badge" to MaterialSymbol("app_badging"),
        "arrow.backward" to MaterialSymbol("arrow_back"),
        "arrow.forward" to MaterialSymbol("arrow_forward"),
        "arrow.left" to MaterialSymbol("arrow_back"),
        "arrow.right" to MaterialSymbol("arrow_forward"),
        "arrow.up" to MaterialSymbol("arrow_upward"),
        "arrow.down" to MaterialSymbol("arrow_downward"),
        "arrow.right.circle" to MaterialSymbol("arrow_circle_right"),
        "arrow.right.circle.fill" to MaterialSymbol("arrow_circle_right", 1f),
        "arrow.up.circle" to MaterialSymbol("arrow_circle_up"),
        "arrow.up.circle.fill" to MaterialSymbol("arrow_circle_up", 1f),
        "arrow.down.circle" to MaterialSymbol("arrow_circle_down"),
        "arrow.down.circle.fill" to MaterialSymbol("arrow_circle_down", 1f),
        "arrow.clockwise" to MaterialSymbol("refresh"),
        "arrow.counterclockwise" to MaterialSymbol("undo"),
        "arrow.triangle.2.circlepath" to MaterialSymbol("sync"),
        "arrow.triangle.swap" to MaterialSymbol("swap_vert"),
        "arrow.triangle.turn.up.right.circle" to MaterialSymbol("directions"),
        "arrow.triangle.turn.up.right.circle.fill" to MaterialSymbol("directions", 1f),
        "arrow.triangle.turn.up.right.diamond" to MaterialSymbol("directions"),
        "arrow.triangle.turn.up.right.diamond.fill" to MaterialSymbol("directions", 1f),
        "arrow.up.arrow.down" to MaterialSymbol("swap_vert"),
        "arrow.left.arrow.right" to MaterialSymbol("swap_horiz"),
        "arrow.up.right" to MaterialSymbol("north_east"),
        "arrow.up.left" to MaterialSymbol("north_west"),
        "arrow.turn.up.left" to MaterialSymbol("turn_left"),
        "arrow.turn.up.right" to MaterialSymbol("turn_right"),
        "arrow.uturn.left" to MaterialSymbol("u_turn_left"),
        "arrow.uturn.right" to MaterialSymbol("u_turn_right"),
        "arrow.up.and.down.square" to MaterialSymbol("elevator"),
        "arrow.merge" to MaterialSymbol("merge"),
        "arrow.up.right.square" to MaterialSymbol("open_in_new"),
        "arrow.up.right.square.fill" to MaterialSymbol("open_in_new", 1f),
        "battery.25" to MaterialSymbol("battery_2_bar"),
        "battery.100" to MaterialSymbol("battery_full"),
        "bed.double.fill" to MaterialSymbol("bed", 1f),
        "book.fill" to MaterialSymbol("book", 1f),
        "building.fill" to MaterialSymbol("apartment", 1f),
        "building.2.fill" to MaterialSymbol("domain", 1f),
        "building.columns.fill" to MaterialSymbol("account_balance", 1f),
        "bell" to MaterialSymbol("notifications"),
        "bell.fill" to MaterialSymbol("notifications", 1f),
        "bell.badge" to MaterialSymbol("notifications_active"),
        "bell.badge.fill" to MaterialSymbol("notifications_active", 1f),
        "bell.slash" to MaterialSymbol("notifications_off"),
        "bolt" to MaterialSymbol("bolt"),
        "bolt.fill" to MaterialSymbol("bolt", 1f),
        "bookmark" to MaterialSymbol("bookmark"),
        "bookmark.fill" to MaterialSymbol("bookmark", 1f),
        "bus" to MaterialSymbol("directions_bus"),
        "bus.fill" to MaterialSymbol("directions_bus", 1f),
        "bus.doubledecker" to MaterialSymbol("directions_bus"),
        "cablecar" to MaterialSymbol("gondola_lift"),
        "cablecar.fill" to MaterialSymbol("gondola_lift", 1f),
        "calendar" to MaterialSymbol("calendar_month"),
        "calendar.badge.clock" to MaterialSymbol("calendar_clock"),
        "calendar.badge.exclamationmark" to MaterialSymbol("event_busy"),
        "camera" to MaterialSymbol("photo_camera"),
        "camera.fill" to MaterialSymbol("photo_camera", 1f),
        "character.cursor.ibeam" to MaterialSymbol("text_fields"),
        "chart.bar" to MaterialSymbol("bar_chart"),
        "chart.bar.fill" to MaterialSymbol("bar_chart", 1f),
        "chart.bar.doc.horizontal" to MaterialSymbol("analytics"),
        "chart.line.uptrend.xyaxis" to MaterialSymbol("monitoring"),
        "checkmark" to MaterialSymbol("check"),
        "checkmark.circle" to MaterialSymbol("check_circle"),
        "checkmark.circle.fill" to MaterialSymbol("check_circle", 1f),
        "checkmark.seal.fill" to MaterialSymbol("verified", 1f),
        "chevron.backward" to MaterialSymbol("chevron_backward"),
        "chevron.forward" to MaterialSymbol("chevron_forward"),
        "chevron.left" to MaterialSymbol("chevron_left"),
        "chevron.right" to MaterialSymbol("chevron_right"),
        "chevron.up" to MaterialSymbol("keyboard_arrow_up"),
        "chevron.down" to MaterialSymbol("keyboard_arrow_down"),
        "chevron.compact.up" to MaterialSymbol("keyboard_arrow_up"),
        "chevron.compact.down" to MaterialSymbol("keyboard_arrow_down"),
        "chevron.up.chevron.down" to MaterialSymbol("unfold_more"),
        "circle" to MaterialSymbol("circle"),
        "circle.fill" to MaterialSymbol("circle", 1f),
        "circle.lefthalf.filled" to MaterialSymbol("contrast"),
        "clock" to MaterialSymbol("schedule"),
        "clock.fill" to MaterialSymbol("schedule", 1f),
        "clock.circle" to MaterialSymbol("schedule"),
        "clock.badge" to MaterialSymbol("more_time"),
        "clock.arrow.circlepath" to MaterialSymbol("history"),
        "clock.arrow.2.circlepath" to MaterialSymbol("update"),
        "cloud" to MaterialSymbol("cloud"),
        "cloud.fill" to MaterialSymbol("cloud", 1f),
        "car.fill" to MaterialSymbol("directions_car", 1f),
        "cross.case.fill" to MaterialSymbol("medical_services", 1f),
        "cross.circle" to MaterialSymbol("medical_services"),
        "doc" to MaterialSymbol("description"),
        "doc.fill" to MaterialSymbol("description", 1f),
        "doc.on.doc" to MaterialSymbol("content_copy"),
        "doc.text" to MaterialSymbol("description"),
        "ellipsis" to MaterialSymbol("more_horiz"),
        "ellipsis.circle" to MaterialSymbol("more_horiz"),
        "envelope" to MaterialSymbol("mail"),
        "envelope.fill" to MaterialSymbol("mail", 1f),
        "exclamationmark.bubble" to MaterialSymbol("feedback"),
        "exclamationmark.bubble.fill" to MaterialSymbol("feedback", 1f),
        "exclamationmark.circle" to MaterialSymbol("error"),
        "exclamationmark.circle.fill" to MaterialSymbol("error", 1f),
        "exclamationmark.triangle" to MaterialSymbol("warning"),
        "exclamationmark.triangle.fill" to MaterialSymbol("warning", 1f),
        "eye" to MaterialSymbol("visibility"),
        "eye.fill" to MaterialSymbol("visibility", 1f),
        "eye.slash" to MaterialSymbol("visibility_off"),
        "eye.slash.fill" to MaterialSymbol("visibility_off", 1f),
        "ferry" to MaterialSymbol("directions_boat"),
        "ferry.fill" to MaterialSymbol("directions_boat", 1f),
        "figure.outdoor.cycle" to MaterialSymbol("directions_bike"),
        "figure.stand" to MaterialSymbol("wc"),
        "figure.roll" to MaterialSymbol("accessible"),
        "figure.walk" to MaterialSymbol("directions_walk"),
        "figure.walk.motion" to MaterialSymbol("nordic_walking"),
        "figure.run" to MaterialSymbol("directions_run"),
        "figure.stairs" to MaterialSymbol("stairs"),
        "figure.wave" to MaterialSymbol("emoji_people"),
        "flag" to MaterialSymbol("flag"),
        "flag.fill" to MaterialSymbol("flag", 1f),
        "flag.circle.fill" to MaterialSymbol("flag_circle", 1f),
        "flag.checkered" to MaterialSymbol("sports_score"),
        "flask" to MaterialSymbol("science"),
        "flask.fill" to MaterialSymbol("science", 1f),
        "fuelpump" to MaterialSymbol("local_gas_station"),
        "fork.knife" to MaterialSymbol("restaurant"),
        "gear" to MaterialSymbol("settings"),
        "gearshape" to MaterialSymbol("settings"),
        "gearshape.fill" to MaterialSymbol("settings", 1f),
        "gearshape.2" to MaterialSymbol("manufacturing"),
        "gearshape.2.fill" to MaterialSymbol("manufacturing", 1f),
        "globe" to MaterialSymbol("language"),
        "hand.draw.fill" to MaterialSymbol("pan_tool_alt", 1f),
        "hand.tap" to MaterialSymbol("touch_app"),
        "hand.tap.fill" to MaterialSymbol("touch_app", 1f),
        "hand.wave" to MaterialSymbol("waving_hand"),
        "hand.wave.fill" to MaterialSymbol("waving_hand", 1f),
        "hare" to MaterialSymbol("cruelty_free"),
        "hare.fill" to MaterialSymbol("sprint", 1f),
        "heart" to MaterialSymbol("favorite"),
        "heart.fill" to MaterialSymbol("favorite", 1f),
        "heart.circle" to MaterialSymbol("favorite"),
        "heart.slash" to MaterialSymbol("heart_broken"),
        "house" to MaterialSymbol("home"),
        "house.fill" to MaterialSymbol("home", 1f),
        "icloud.slash" to MaterialSymbol("cloud_off"),
        "icloud.slash.fill" to MaterialSymbol("cloud_off", 1f),
        "info.circle" to MaterialSymbol("info"),
        "info.circle.fill" to MaterialSymbol("info", 1f),
        "iphone" to MaterialSymbol("smartphone"),
        "ladybug" to MaterialSymbol("bug_report"),
        "ladybug.fill" to MaterialSymbol("bug_report", 1f),
        "leaf" to MaterialSymbol("eco"),
        "leaf.fill" to MaterialSymbol("eco", 1f),
        "lightbulb" to MaterialSymbol("lightbulb"),
        "lightbulb.fill" to MaterialSymbol("lightbulb", 1f),
        "link" to MaterialSymbol("link"),
        "list.bullet" to MaterialSymbol("format_list_bulleted"),
        "list.bullet.indent" to MaterialSymbol("format_indent_increase"),
        "list.star" to MaterialSymbol("featured_play_list"),
        "location" to MaterialSymbol("near_me"),
        "location.fill" to MaterialSymbol("near_me", 1f),
        "location.circle" to MaterialSymbol("my_location"),
        "location.circle.fill" to MaterialSymbol("my_location", 1f),
        "location.north.fill" to MaterialSymbol("navigation", 1f),
        "location.north.line.fill" to MaterialSymbol("assistant_navigation", 1f),
        "location.slash" to MaterialSymbol("location_off"),
        "location.slash.fill" to MaterialSymbol("location_off", 1f),
        "lock" to MaterialSymbol("lock"),
        "lock.fill" to MaterialSymbol("lock", 1f),
        "lock.shield" to MaterialSymbol("security"),
        "lock.shield.fill" to MaterialSymbol("security", 1f),
        "magnifyingglass" to MaterialSymbol("search"),
        "map" to MaterialSymbol("map"),
        "map.fill" to MaterialSymbol("map", 1f),
        "mappin" to MaterialSymbol("location_on"),
        "mappin.circle.fill" to MaterialSymbol("location_on", 1f),
        "mappin.and.ellipse" to MaterialSymbol("pin_drop"),
        "parkingsign.circle.fill" to MaterialSymbol("local_parking", 1f),
        "pawprint.fill" to MaterialSymbol("pets", 1f),
        "minus" to MaterialSymbol("remove"),
        "minus.circle" to MaterialSymbol("do_not_disturb_on"),
        "minus.circle.fill" to MaterialSymbol("do_not_disturb_on", 1f),
        "moon" to MaterialSymbol("dark_mode"),
        "moon.fill" to MaterialSymbol("dark_mode", 1f),
        "music.note" to MaterialSymbol("music_note"),
        "network" to MaterialSymbol("public"),
        "paintbrush" to MaterialSymbol("brush"),
        "paintbrush.fill" to MaterialSymbol("brush", 1f),
        "paintpalette" to MaterialSymbol("palette"),
        "paintpalette.fill" to MaterialSymbol("palette", 1f),
        "paperplane" to MaterialSymbol("send"),
        "paperplane.fill" to MaterialSymbol("send", 1f),
        "pause.fill" to MaterialSymbol("pause", 1f),
        "pencil" to MaterialSymbol("edit"),
        "person" to MaterialSymbol("person"),
        "person.fill" to MaterialSymbol("person", 1f),
        "person.2" to MaterialSymbol("group"),
        "person.2.fill" to MaterialSymbol("group", 1f),
        "person.3" to MaterialSymbol("groups"),
        "person.3.fill" to MaterialSymbol("groups", 1f),
        "person.crop.circle" to MaterialSymbol("account_circle"),
        "person.crop.circle.fill" to MaterialSymbol("account_circle", 1f),
        "person.text.rectangle" to MaterialSymbol("badge"),
        "person.text.rectangle.fill" to MaterialSymbol("badge", 1f),
        "phone" to MaterialSymbol("call"),
        "phone.fill" to MaterialSymbol("call", 1f),
        "photo" to MaterialSymbol("image"),
        "photo.fill" to MaterialSymbol("image", 1f),
        "play.fill" to MaterialSymbol("play_arrow", 1f),
        "plus" to MaterialSymbol("add"),
        "plus.circle" to MaterialSymbol("add_circle"),
        "plus.circle.fill" to MaterialSymbol("add_circle", 1f),
        "point.bottomleft.forward.to.point.topright.filled.scurvepath" to MaterialSymbol("route"),
        "point.bottomleft.forward.to.point.topright.scurvepath" to MaterialSymbol("route"),
        "printer" to MaterialSymbol("print"),
        "qrcode" to MaterialSymbol("qr_code"),
        "qrcode.viewfinder" to MaterialSymbol("qr_code_scanner"),
        "questionmark" to MaterialSymbol("question_mark"),
        "questionmark.circle" to MaterialSymbol("help"),
        "questionmark.circle.fill" to MaterialSymbol("help", 1f),
        "rectangle.compress.vertical" to MaterialSymbol("compress"),
        "rectangle.expand.vertical" to MaterialSymbol("expand"),
        "scooter" to MaterialSymbol("electric_scooter"),
        "shippingbox" to MaterialSymbol("inventory_2"),
        "shippingbox.fill" to MaterialSymbol("inventory_2", 1f),
        "signpost.right" to MaterialSymbol("signpost"),
        "signpost.right.fill" to MaterialSymbol("signpost", 1f),
        "slider.horizontal.3" to MaterialSymbol("tune"),
        "shield.fill" to MaterialSymbol("shield", 1f),
        "snowflake" to MaterialSymbol("ac_unit"),
        "sparkles" to MaterialSymbol("auto_awesome"),
        "speaker.wave.2" to MaterialSymbol("volume_up"),
        "speaker.wave.2.fill" to MaterialSymbol("volume_up", 1f),
        "square" to MaterialSymbol("square"),
        "square.and.arrow.up" to MaterialSymbol("ios_share"),
        "square.and.arrow.up.fill" to MaterialSymbol("ios_share", 1f),
        "square.and.pencil" to MaterialSymbol("edit_square"),
        "star" to MaterialSymbol("star"),
        "star.fill" to MaterialSymbol("star", 1f),
        "star.slash" to MaterialSymbol("star_half"),
        "stop.fill" to MaterialSymbol("stop", 1f),
        "sun.max" to MaterialSymbol("light_mode"),
        "sun.max.fill" to MaterialSymbol("light_mode", 1f),
        "theatermasks.fill" to MaterialSymbol("theater_comedy", 1f),
        "tree.fill" to MaterialSymbol("park", 1f),
        "textformat" to MaterialSymbol("text_format"),
        "thermometer.medium" to MaterialSymbol("device_thermostat"),
        "ticket" to MaterialSymbol("confirmation_number"),
        "ticket.fill" to MaterialSymbol("confirmation_number", 1f),
        "timer" to MaterialSymbol("timer"),
        "train.side.front.car" to MaterialSymbol("train"),
        "tortoise.fill" to MaterialSymbol("elderly", 1f),
        "tram" to MaterialSymbol("tram"),
        "tram.fill" to MaterialSymbol("tram", 1f),
        "tram.tunnel.fill" to MaterialSymbol("train", 1f),
        "trash" to MaterialSymbol("delete"),
        "trash.fill" to MaterialSymbol("delete", 1f),
        "trash.circle.fill" to MaterialSymbol("delete", 1f),
        "trophy" to MaterialSymbol("trophy"),
        "trophy.fill" to MaterialSymbol("trophy", 1f),
        "washer.fill" to MaterialSymbol("local_laundry_service", 1f),
        "water.waves" to MaterialSymbol("waves"),
        "wand.and.stars" to MaterialSymbol("auto_fix_high"),
        "wave.3.forward" to MaterialSymbol("contactless"),
        "wifi" to MaterialSymbol("wifi"),
        "wifi.exclamationmark" to MaterialSymbol("signal_wifi_bad"),
        "wifi.slash" to MaterialSymbol("wifi_off"),
        "wrench" to MaterialSymbol("build"),
        "wrench.fill" to MaterialSymbol("build", 1f),
        "xmark" to MaterialSymbol("close"),
        "xmark.circle" to MaterialSymbol("cancel"),
        "xmark.circle.fill" to MaterialSymbol("cancel", 1f)
    )

    fun glyphFor(sfName: String): MaterialSymbol {
        return map[sfName] ?: MaterialSymbol("question_mark")
    }
}
